### ISSUE TITLE
Appropriate response when some subscribed properties don't exist

### ISSUE THREAD

**Issue by wmww** [OpenStarscape/starscape-protocol#3]
If a property that doesn't exist is gotten, the server should presumably reply with `"no such property"`, but what if one of the properties subscribed to doesn't exist, but others do. Do we still send `"no such property"`? Do we invalidate the subscription to the properties that did work?

**Comment by ghost** [comment]
Perhaps the server includes a list of which properties didn't exist, under a name such as `badproperties`?

**Comment by ghost** [comment]
In that case, the remaining properties would be subscribed, and the client would know exactly what went wrong.

**Comment by ghost** [comment]
We could also simply never send any updates for an unknown property.

**Comment by wmww** [comment]
It is no longer possible to subscribe to multiple properties at once
