### ISSUE TITLE
Reduce message size

### ISSUE THREAD

**Issue by wmww** [OpenStarscape/starscape-protocol#5]
I don't foresee our required bandwidth being so low that it can be considered "good enough" for any connection a client may want. Therefore, we should consider how we might make our messages smaller. I see three ways we may be able to make improvements:

## Optimize JSON schema
For example, change `"position":{"x":0.0,"y":0.0,"z":0.0}` to `"p":[0.0,0.0,0.0]`. This sacrifices a small amount of readability of the raw protocol for potentially significant (although not huge) performance gains.

## Compress JSON
As suggested by @alexbuzzbee when I brought up the question on Matrix. May significantly reduce data size of JSON.

## Use a fully binary format
I suspect that an uncompressed format would be smaller than compressed JSON with the same information, but this has yet to be tested. It would almost certainly be faster to serialize and deserialize (and maybe even faster than uncompressed JSON?). The cost is potential bloat and lack of portability of the client library.

**Comment by wmww** [comment]
[Here](https://leopard.in.ua/2013/10/13/binary-serialization-formats) is a good list of potential binary formats with pertinent info. The candidates I've come across not on that list are [CBOR](https://cbor.io/spec.html) and [PSON](https://github.com/dcodeIO/PSON).

**Comment by ghost** [comment]
CBOR is better-standardized (lots of implementations) and has explicit support for framing (which I didn't see in PSON, though it might be there), so I'd prefer that. It will probably be faster than compressing JSON (compression is kind of slow).

**Comment by wmww** [comment]
No longer relevant
